config/routes.rb
Rails.application.routes.draw do

  resources :charges
  
  devise_for :users
  resources :products do
      resources :orders, only: [:new, :create]
  end

  get 'page/about'
  get 'page/contact'
  get 'seller', to: "products#seller"
  get 'sales', to: "orders#sales"
  get  'purchases', to: "order#purchases"

  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :address, :city, :state, presence: true

  belongs_to :product
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"
end

app/models/product.rb
class Product < ApplicationRecord

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "default.png"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :name, :description, :price, presence: true
  validates :price, numericality: {greater_than: 0}

  belongs_to :user
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

        validates :name, presence: true

        has_many :products, dependent: :destroy
        has_many :sales, class_name: "Order", foreign_key: "seller_id"
        has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    amount = params[:stripeAmount].to_i * 100

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => @description,
      :currency    => 'au',
      :receipt_email => @user_email,
      :source => token,
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
    flash[:notice] = "Please try again"
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /orders
  # GET /orders.json

  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC ")
  end

  def purchases
      @orders = Order.all.where(buyer: current_user).order("created_at DESC ")
  end



  # GET /orders/new
  def new
    @order = Order.new
    @product = Product.find(params[:product_id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @product = Product.find(params[:product_id])
    @seller = @product.user

    @order.product_id = @product.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def seller
    @products = Product.where(user:current_user)
  end

  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end

    def check_user
      if current_user != @product.user_id
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do -%>
 <article>
     <%= label_tag 'amount', 'To Pay', class: 'amount' %>
     <%= label_tag 'amount', "$#{@amount}.00", class: 'amount-figure' %>
 </article>

 <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Settings[Rails.env]['stripe']['publishable_key'] %>"
    data-description="Your payment description"
    data-amount="<%= @amount * 100 %>">
  </script>
<% end %>

app/views/layouts/_footer.html.erb
<p>
  Copyright 2017
</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Taste Of ..</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", page_about_path %></li>
        <li><%= link_to "Contact", page_contact_path %></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Seller Account <span class="caret"></span></a>
             <ul class="dropdown-menu">
               <li><%= link_to "Manage Listings", seller_path %></li>
               <li><% link_to "Sales History", sales_path %></li>
             </ul>
           </li>

           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><% link_to "Purchase History", purchases_path %></li>
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>

        <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>

          <li><%= link_to "Sign In", new_user_session_path %></li>
         <% end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasteof</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% javascript_include_tag "https:js.stripe.com/v2/" %>
    <%= csrf_meta_tags %>
    <%= tag :meta, name: "stripe-key", content: ENV["STRIPE_PUBLIC_KEY"] %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name,msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <%= content_tag :div, msg, id: "flash_#(name)"%>
            </div>
          <% end %>
        <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
        </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag @product.image.url %>
    </div>
    <h3><%= @product.name %></h3>
    <h3><%= number_to_currency(@product.price)%></h3>
  </div>
</div>





<%= form_for([@product, @order]) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation" class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h>

        <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
        </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: "form-control" %>
  </div>

  <form action="/your-server-side-code" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_Kac1zzPeaCgEOKiL9kjYz0Ct"
    data-amount="999"
    data-name="Demo Site"
    data-description="Widget"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto"
    data-zip-code="true"
    data-currency="aud">
  </script>
</form>
<br />
  <div class="form-group">
    <%= f.submit "Next", class: "btn btn-success" %>
  </div>
<% end %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', product_orders_path %>

app/views/orders/purchases.html.erb
<div class="class">
  <h2>Your Purchase History</h2>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Item </th>
    <th class="center">Price</th>
    <th class="center">Seller</th>
    <th class="center">Date Purchased</th>
  </tr>

  <% @orders.each do |order| %>
  <tr>
    <td class="center"> <%=image_tag order.image.url(:thumb) %></td>
    <td class="center"> <%=order.product.name %></td>
    <td class="center"> <%=number_to_currency(order.product.price) %></td>
    <td class="center"> <%= order.seller.name %></td>
    <td class="center"> <%= order.created_at.strftime("%-d %B %Y") %></td>
  </tr>
  <% end %>
</table>


<% if (user_signed_in?) %>
  <%= link_to 'New Product', new_product_path, class: "btn btn-link" %>
<% end %>

app/views/orders/sales.html.erb
<div class="class">
  <h2>Your Sales History</h2>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Item </th>
    <th class="center">Price</th>
    <th class="center">Customer</th>
    <th class="center">Date Sold</th>
  </tr>

  <% @orders.each do |order| %>
  <tr>
    <td> <%=image_tag order.image.url(:thumb) %></td>
    <td> <%=order.product.name %></td>
    <td> <%=number_to_currency(order.product.price) %></td>
    <td> <%= order.buyer.name %></td>
    <td> <%= order.created_at.strftime("%-d %B %Y") %></td>
  </tr>
  <% end %>
</table>


<% if (user_signed_in?) %>
  <%= link_to 'New Product', new_product_path, class: "btn btn-link" %>
<% end %>

app/views/page/about.html.erb
<h1>About</h1>
<p>Taste of is an Australian Owned and opperated business making the process of getting great eats easier. </p>

app/views/page/contact.html.erb
<h1>Get in Touch</h1>
<p>Email us at Tasteof@gmail.com</p>

app/views/products/_form.html.erb
<%= form_for(product, html: {multipart: true }) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h4>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product, class: "btn btn-link" %> |
<%= link_to 'Back', products_path, class: "btn btn-link" %>

app/views/products/index.html.erb
<div class="jumbotron">
<h1>Delicious Produce from<br /> around Australia</h1>
<h2>Discover locally made food</h2>
</div>
<div class="center">
  <div class="row">
      <% @products.each do |product| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag(product.image.url), product %>

        <div class="caption">
          <h3><%= product.name %></h3>
          <p><%= number_to_currency(product.price) %></p>
       <p>
            <%= "Sold by #{product.user.name}" %>
           </p>
           <% if (user_signed_in?) && (current_user == product.user) %>
            <%= link_to 'Edit', edit_product_path(product), class: "btn btn-link" %>
            <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
            <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<br>
<% if (user_signed_in?) %>
  <%= link_to 'New Product', new_product_path, class: "btn btn-link" %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product, class: "btn btn-link" %>

<%= link_to 'Back', products_path, class: "btn btn-link" %>

app/views/products/seller.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name </th>
    <th class="center">Description</th>
    <th class="center">Description</th>
    <th class="center">Price</th>
    <th class="center">Action</th>
  </tr>

  <% @products.each do |product| %>
  <tr>
  <td> <%=image_tag product.image.url(:thumb) %></td>
  <td> <%=product.name %></td>
  <td> <%=product.description %></td>
  <td> <%= number_to_currency(product.price) %></td>
  <td>
    <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Action <span class="caret"></span>
        </button>
      <ul class="dropdown-menu">
        <li><%= link_to "View", product, class: "btn btn-link" %></li>
        <li><%= link_to "Edit", edit_product_path(product), class: "btn btn-link" %></li>
        <li><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?', class: "btn btn-link" } %></li>
      </ul>
    </div>

  </td>
</tr>
<% end %>
</table>


<% if (user_signed_in?) %>
  <%= link_to 'New Product', new_product_path, class: "btn btn-link" %>
<% end %>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
    <%= image_tag @product.image.url %>
  </div>
  </div>
  <div class="col-md-6">
    <h3>  <%= @product.name %> </h3>
    <p>  <%= number_to_currency(@product.price) %>  </p>
    <p><%= @product.description %></p>
    <br />
    <div class="center">
      <%= link_to "Buy It Now", new_product_order_path(@product), class: "btn btn-primary" %>
      </div>
  </div>
</div>

<% if current_user == @product_user %>
<%= link_to 'Edit', edit_product_path(@product), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', products_path, class: "btn btn-link" %>